openapi: 3.0.0
info:
  title: Task Manager API
  version: 1.0.0
  description: API para gerenciamento de tarefas
paths:
  /task:
    get:
      summary: Lista todas as tarefas
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Cria uma nova tarefa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Tarefa criada com sucesso
  /task/{id}:
    get:
      summary: Obtém uma tarefa pelo ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID da tarefa
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tarefa não encontrada
    put:
      summary: Atualiza uma tarefa existente
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID da tarefa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Tarefa atualizada com sucesso
        '404':
          description: Tarefa não encontrada
    delete:
      summary: Deleta uma tarefa
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID da tarefa
      responses:
        '204':
          description: Tarefa deletada com sucesso
        '404':
          description: Tarefa não encontrada
  /user/create:
    post:
      summary: Cadastra novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '500':
          description: Falha interna
  /session/authenticate:
    post:
      summary: Autentica se a sessão está válida
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Session'
      responses:
        '200':
          description: Sucesso ao autenticar sessão
        '500':
          description: Falha interna
  /status/:
    get:
      summary: Busca todas as autenticações feitas
      responses:
        '201':
          description: Autenticações válidas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Authentication'
        '500':
          description: Falha interna
  /status/task:
    get:
      summary: Busca as autenticações para uma determinada tarefa
      parameters:
        - in: query
          name: taskId
          schema:
            type: integer
          required: true
          description: ID da tarefa
      responses:
        '201':
          description: Autenticações válidas para a tarefa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Authentication'
        '500':
          description: Falha interna
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        password:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Session:
      type: object
      properties:
        sessionId:
          type: string
        userId:
          type: integer
        createdAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time
    Authentication:
      type: object
      properties:
        sessionId:
          type: string
        taskId:
          type: integer
        authenticatedAt:
          type: string
          format: date-time
