openapi: 3.0.0
info:
  title: Task Manager API
  version: 1.0.0
  description: API para gerenciamento de tarefas
paths:
  /tasks:
    get:
      summary: Lista todas as tarefas
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Cria uma nova tarefa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Tarefa criada com sucesso
  /tasks/{id}:
    get:
      summary: Obtém uma tarefa pelo ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID da tarefa
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tarefa não encontrada
    put:
      summary: Atualiza uma tarefa existente
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID da tarefa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Tarefa atualizada com sucesso
        '404':
          description: Tarefa não encontrada
    delete:
      summary: Deleta uma tarefa
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID da tarefa
      responses:
        '204':
          description: Tarefa deletada com sucesso
        '404':
          description: Tarefa não encontrada
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time